### ISSUE TITLE
translation missing: ru.subtask_list_columns

### ISSUE THREAD

**Issue by Pazus** [SMS-IT/redmine_subtask_list_columns#7]
Hi.

I can't get into plugin configuration page, the link is named as "translation missing: ru.subtask_list_columns".

If I try to open a task with child issues I catch "Internal error". I'll provide logs soon.

**Comment by shaiku** [comment]
They're not joking when they say to be sure to install to **plugins/subtask_list_columns**

git clone will install to **redmine_**subtask_list_columns and you will have these problems.  I was able to fix it by renaming the directory and re-running "rake redmine:plugins:migrate RAILS_ENV=production"

Good luck!

**Comment by Pazus** [comment]
Reinstalled into plugins folder but still:

`Started GET "/issues/3540" for 10.10.24.3 at 2016-02-10 11:15:18 +0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"3540"}
  Current user: Roman.gromov (id=118)
  Rendered issues/_action_menu.html.erb (6.5ms)
  Rendered plugins/clear_plan/app/views/clear_plan/hooks/_issue_bottom_details.html.erb (0.1ms)
  Rendered plugins/unread_issues/app/views/hooks/unread_isues/_issue_bottom_details.html.erb (0.1ms)
  Rendered attachments/_links.html.erb (4.8ms)
  Rendered issues/show.html.erb within layouts/base (122.1ms)
Completed 500 Internal Server Error in 304ms (ActiveRecord: 10.6ms)

ActionView::Template::Error (undefined method `get_fields_for_project' for #<#<Class:0x00000004c18b40>:0x007fa256e59f48>):
     98:   <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
     99: </div>
    100: <p><strong><%=l(:label_subtask_plural)%></strong></p>
    101: <%= render_descendants_tree(@issue) unless @issue.leaf? %>
    102: </div>
    103: <% end %>
    104: 
  app/views/issues/show.html.erb:101:in`_app_views_issues_show_html_erb___1632689785382741017_39765080'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in`show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Comment by CarbonUnit** [comment]
@Pazus I get this same error.  Any resolution?  Thanks!

Completed 500 Internal Server Error in 470ms (ActiveRecord: 29.5ms)

ActionView::Template::Error (undefined method `get_fields_for_project' for #<#<Class:0x00007faa4ab0ac10>:0x00007faa4b835ea8>):
    104: </div>
    105: <p><strong><%=l(:label_subtask_plural)%></strong></p>
    106: <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
    107: <%= render_descendants_tree(@issue) unless @issue.leaf? %>
    108: <% end %>
    109: </div>
    110: <% end %>
  plugins/subtask_list_columns/lib/subtask_list_columns_lib.rb:19:in `render_descendants_tree_with_listed'
  app/views/issues/show.html.erb:107:in `block in _app_views_issues_show_html_erb___2101165390499479270_70184695086860'
  app/views/issues/show.html.erb:106:in `_app_views_issues_show_html_erb___2101165390499479270_70184695086860'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by igor-panassiouk** [comment]
Same problem

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.10
